#! /bin/sh

certbot certonly \
  -n \
  --agree-tos \
  --email $1 \
  --dns-cloudflare \
  --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini \
  --rsa-key-size 4096 \
  -d $2

cp -Lr /etc/letsencrypt/live/* /certs